#!/bin/bash
# Interactive setup script for Threads API credentials
# Safely guides user through token and user ID configuration

ENV_FILE="$(dirname "$0")/../.env"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     Threads API — Environment Setup      ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  source "$ENV_FILE"
  if [ -n "$THREADS_ACCESS_TOKEN" ] && [ "$THREADS_ACCESS_TOKEN" != "your_token_here" ] && [ -n "$THREADS_USER_ID" ] && [ "$THREADS_USER_ID" != "your_user_id_here" ]; then
    echo -e "${GREEN}✓ .env already configured${NC}"
    echo ""
    echo "  Token:   ${THREADS_ACCESS_TOKEN:0:8}...${THREADS_ACCESS_TOKEN: -4}"
    echo "  User ID: $THREADS_USER_ID"
    echo ""
    read -p "Do you want to reconfigure? (y/N) " RECONFIG
    if [ "$RECONFIG" != "y" ] && [ "$RECONFIG" != "Y" ]; then
      echo "Keeping existing config."
      exit 0
    fi
  fi
fi

echo "This script will help you configure your Threads API credentials."
echo ""
echo "You need:"
echo "  1. A Threads Access Token (from Meta Graph API Explorer)"
echo "  2. Your Threads User ID"
echo ""
echo "Token types:"
echo "  • Graph API Explorer tokens are long-lived (60 days)"
echo "  • Short-lived tokens expire in 1 hour — you can exchange them below"
echo ""

# Step 1 — Token
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " STEP 1: Get your Access Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Go to https://developers.facebook.com/"
echo "  2. Create a new app (Business type)"
echo "  3. Add the 'Threads' use case"
echo "  4. Go to https://developers.facebook.com/tools/explorer/"
echo "  5. Select your app from the dropdown"
echo "  6. Click 'Generate Access Token'"
echo "  7. Check these permissions:"
echo ""
echo "     threads_basic"
echo "     threads_content_publish"
echo "     threads_manage_insights"
echo "     threads_manage_replies"
echo "     threads_read_replies"
echo "     threads_manage_mentions"
echo "     threads_keyword_search"
echo ""
echo "  8. Authorize and copy the token"
echo ""

read -p "Paste your access token: " INPUT_TOKEN

if [ -z "$INPUT_TOKEN" ]; then
  echo -e "${RED}✗ No token provided. Aborting.${NC}"
  exit 1
fi

# Validate token by calling API
echo ""
echo -n "Validating token... "
API_RESPONSE=$(curl -s "https://graph.threads.net/v1.0/me?fields=id,username&access_token=$INPUT_TOKEN" 2>&1)

if echo "$API_RESPONSE" | python3 -c "import sys,json; json.load(sys.stdin)" 2>/dev/null; then
  USERNAME=$(echo "$API_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('username',''))")
  USER_ID=$(echo "$API_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))")

  if [ -n "$USER_ID" ]; then
    echo -e "${GREEN}✓ Valid!${NC}"
    echo ""
    echo "  Detected: @$USERNAME (ID: $USER_ID)"
    echo "  Token type: long-lived (60 days)"
    echo ""
    read -p "Use this user ID? (Y/n) " USE_ID
    if [ "$USE_ID" = "n" ] || [ "$USE_ID" = "N" ]; then
      read -p "Enter your user ID: " INPUT_USER_ID
    else
      INPUT_USER_ID="$USER_ID"
    fi
  else
    echo -e "${RED}✗ Invalid token or no user found${NC}"
    read -p "Enter your user ID manually: " INPUT_USER_ID
  fi
else
  echo -e "${RED}✗ Token validation failed${NC}"
  echo ""
  echo "  Response: $API_RESPONSE"
  echo ""
  read -p "Enter your user ID manually (or press Enter to abort): " INPUT_USER_ID
  if [ -z "$INPUT_USER_ID" ]; then
    exit 1
  fi
fi

# Short-lived token exchange option
echo ""
read -p "Is this a short-lived token (expires in 1 hour)? Exchange for long-lived? (y/N) " EXCHANGE
if [ "$EXCHANGE" = "y" ] || [ "$EXCHANGE" = "Y" ]; then
  echo ""
  echo "To exchange, you need your App ID and App Secret from https://developers.facebook.com/"
  echo ""
  read -p "App ID: " APP_ID
  read -p "App Secret: " APP_SECRET

  if [ -n "$APP_ID" ] && [ -n "$APP_SECRET" ]; then
    echo -n "Exchanging token... "
    EXCHANGE_RESPONSE=$(curl -s "https://graph.threads.net/v1.0/access_token?grant_type=fb_exchange_token&client_id=$APP_ID&client_secret=$APP_SECRET&fb_exchange_token=$INPUT_TOKEN" 2>&1)

    NEW_TOKEN=$(echo "$EXCHANGE_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null)

    if [ -n "$NEW_TOKEN" ] && [ "$NEW_TOKEN" != "" ]; then
      INPUT_TOKEN="$NEW_TOKEN"
      echo -e "${GREEN}✓ Exchanged!${NC}"
      echo "  New token: ${INPUT_TOKEN:0:8}...${INPUT_TOKEN: -4}"
    else
      echo -e "${RED}✗ Exchange failed${NC}"
      echo "  Response: $EXCHANGE_RESPONSE"
      echo "  Keeping original token."
    fi
  else
    echo "Missing credentials — keeping original token."
  fi
fi

# Write .env
echo ""
echo -n "Writing .env... "

cat > "$ENV_FILE" <<EOF
# Threads API Credentials
# Generated by setup script on $(date)
THREADS_ACCESS_TOKEN=$INPUT_TOKEN
THREADS_USER_ID=$INPUT_USER_ID
EOF

chmod 600 "$ENV_FILE"

echo -e "${GREEN}✓ Done!${NC}"
echo ""
echo "  .env saved to: $ENV_FILE"
echo "  (file permissions set to 600 — owner-only read/write)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Test it:"
echo "   ./scripts/threads.sh profile"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
